import { IInventoryState } from "./types";

export const mockState: IInventoryState = {
	items: [
		{
			type: "clothes",
			metadatas: { variationId: 0, renamed: "Chaussures N°139", drawableId: 139 },
			rows: 1,
			weight: 0.1,
			count: 1,
			label: "Chaussures",
			cols: 1,
			name: "feet",
		},
		{
			type: "clothes",
			metadatas: { variationId: 0, renamed: "Lunettes N°0", drawableId: 0 },
			rows: 1,
			weight: 0.1,
			count: 1,
			label: "Lunettes",
			cols: 1,
			name: "glasses",
		},
		{
			type: "clothes",
			metadatas: { variationId: 7, renamed: "Masque N°51", name: "mask", drawableId: 51 },
			rows: 1,
			weight: 0.1,
			count: 1,
			label: "Masque",
			cols: 1,
			name: "mask",
		},
		{
			type: "clothes",
			metadatas: {
				variationArmsId: 0,
				variationTorsoId: 1,
				drawableTorsoId: 22,
				drawableTshirtId: 15,
				renamed: "Haut N°22",
				drawableArmsId: 19,
				variationTshirtId: 0,
			},
			rows: 1,
			weight: 0.1,
			count: 1,
			label: "T-shirt",
			cols: 1,
			name: "tshirt",
		},
		{
			type: "clothes",
			metadatas: { variationId: 1, renamed: "Collier #238", drawableId: 238 },
			rows: 1,
			weight: 0.1,
			count: 1,
			label: "Collier",
			cols: 1,
			name: "collier",
		},
		{
			type: "clothes",
			metadatas: { variationId: 1, renamed: "Bague #137", drawableId: 137 },
			rows: 1,
			weight: 0.1,
			count: 1,
			label: "Bague",
			cols: 1,
			name: "bague",
		},
		{
			type: "weapons",
			metadatas: { ammo: 6 },
			rows: 2,
			weight: 8.0,
			count: 1,
			label: "Fusil L96A1",
			cols: 4,
			name: "weapon_sniperrifle",
		},
		{
			type: "items",
			metadatas: { plate: "RTPY0654", renamed: "RTPY0654-10F Widebody", canRename: false },
			rows: 1,
			weight: 0.1,
			count: 1,
			label: "clé",
			cols: 1,
			name: "keys",
		},
		{ type: "items", rows: 1, weight: 0.1, count: 1, label: "Téléphone", cols: 1, name: "phone" },
		{
			type: "items",
			metadatas: { plate: "CSJB6866", renamed: "CSJB6866-Bati 901", canRename: false },
			rows: 1,
			weight: 0.1,
			count: 1,
			label: "clé",
			cols: 1,
			name: "keys",
		},
		{
			type: "clothes",
			metadatas: { variationId: 4, renamed: "Sac N°212", name: "sac", drawableId: 212 },
			rows: 1,
			weight: 0.1,
			count: 1,
			label: "Accessoire",
			cols: 1,
			name: "access",
		},
		{
			type: "items",
			metadatas: { plate: "EFBT8927", renamed: "EFBT8927-Jugular", canRename: false },
			rows: 1,
			weight: 0.1,
			count: 1,
			label: "clé",
			cols: 1,
			name: "keys",
		},
		{
			type: "clothes",
			metadatas: { variationId: 0, renamed: "Pantalon N°248", drawableId: 248 },
			rows: 1,
			weight: 0.1,
			count: 1,
			label: "Pantalon",
			cols: 1,
			name: "pant",
		},
		{
			type: "items",
			metadatas: { plate: "ZLSM5700", renamed: "ZLSM5700-Argento 2", canRename: false, premium: true },
			rows: 1,
			weight: 0.1,
			count: 1,
			label: "clé",
			cols: 1,
			name: "keys",
		},
		{
			type: "items",
			metadatas: { plate: "09TKZ195", renamed: "09TKZ195-Ambulance SAMS", canRename: false },
			rows: 1,
			weight: 0.1,
			count: 1,
			label: "clé",
			cols: 1,
			name: "keys",
		},
		{
			type: "items",
			metadatas: { plate: "YLET6186", renamed: "YLET6186-Toros", canRename: false, premium: true },
			rows: 1,
			weight: 0.1,
			count: 1,
			label: "clé",
			cols: 1,
			name: "keys",
		},
		{
			type: "clothes",
			metadatas: {
				drawableArmsId: 4,
				variationArmsId: 0,
				drawableTorsoId: 696,
				variationTorsoId: 2,
				drawableTshirtId: 15,
				renamed: "Sweat N°696",
				variationTshirtId: 0,
				premium: true,
			},
			rows: 1,
			weight: 0.1,
			count: 1,
			label: "T-shirt",
			cols: 1,
			name: "tshirt",
		},
		{
			type: "items",
			metadatas: { plate: "65ZKX414", renamed: "65ZKX414-Fieldmaster", canRename: false },
			rows: 1,
			weight: 0.1,
			count: 1,
			label: "clé",
			cols: 1,
			name: "keys",
		},
		{
			type: "items",
			metadatas: { plate: "26XSM854", renamed: "26XSM854-Fieldmaster", canRename: false },
			rows: 1,
			weight: 0.1,
			count: 1,
			label: "clé",
			cols: 1,
			name: "keys",
		},
		{ type: "items", rows: 1, weight: 0.0, count: 99661287, label: "Argent", cols: 1, name: "money" },
		{
			type: "items",
			metadatas: { plate: "OCUS2683", renamed: "OCUS2683-NULL", canRename: false, premium: true },
			rows: 1,
			weight: 0.1,
			count: 1,
			label: "clé",
			cols: 1,
			name: "keys",
		},
		{ type: "weapons", metadatas: { ammo: 0 }, rows: 1, weight: 0.3, count: 1, label: "Couteau", cols: 1, name: "weapon_knife" },
		{ type: "items", rows: 1, weight: 0.1, count: 4, label: "Musquet Ammo", cols: 1, name: "ammo_musquet" },
		{
			type: "items",
			metadatas: { plate: "GZIE1270", renamed: "GZIE1270-Novaja Papka", canRename: false, premium: true },
			rows: 1,
			weight: 0.1,
			count: 1,
			label: "clé",
			cols: 1,
			name: "keys",
		},
		{
			type: "items",
			metadatas: { plate: "DOSB0963", renamed: "DOSB0963-Pisswasser Dominator", canRename: false, premium: true },
			rows: 1,
			weight: 0.1,
			count: 1,
			label: "clé",
			cols: 1,
			name: "keys",
		},
		{
			type: "items",
			metadatas: { plate: "KDUC2849", renamed: "KDUC2849-Buffalo SX Unmarked", canRename: false, premium: true },
			rows: 1,
			weight: 0.1,
			count: 1,
			label: "clé",
			cols: 1,
			name: "keys",
		},
		{ type: "items", rows: 1, weight: 1.0, count: 1, label: "LifeInvader", cols: 1, name: "tabletli" },
		{ type: "items", rows: 1, weight: 1.0, count: 1, label: "MDT", cols: 1, name: "tabletmdt" },
		{ type: "weapons", metadatas: { ammo: 1 }, rows: 1, weight: 0.2, count: 5, label: "Grenade", cols: 1, name: "weapon_grenade" },
		{ type: "weapons", metadatas: { ammo: 30 }, rows: 2, weight: 4.0, count: 1, label: "M4A1", cols: 3, name: "weapon_carbinerifle" },
		{
			type: "weapons",
			metadatas: { ammo: 12 },
			rows: 2,
			weight: 2.0,
			count: 1,
			label: "Beretta 92 FS",
			cols: 2,
			name: "weapon_pistol",
		},
		{ type: "items", rows: 1, weight: 0.1, count: 7, label: "Rifle Magazine", cols: 1, name: "ammo_rifle" },
		{ type: "items", rows: 1, weight: 0.1, count: 4, label: "Sniper Magazine", cols: 1, name: "ammo_snip" },
		{
			type: "weapons",
			metadatas: { ammo: 8 },
			rows: 2,
			weight: 2.0,
			count: 1,
			label: "Fusil de laser game",
			cols: 2,
			name: "weapon_laser",
		},
		{
			type: "items",
			metadatas: {
				identity: {
					exp: "4/7/2024",
					class: "Aucun",
					wgt: "60",
					ln: "McMuffin",
					hgt: "170",
					iss: "4/1/2034",
					fn: "Sencule",
					hair: "Brun",
					sex: "M",
					eyes: "caca",
					dob: "1/1/1999",
					dl: 19299,
				},
			},
			rows: 1,
			weight: 0.1,
			count: 1,
			label: "Carte d identité",
			cols: 1,
			name: "identitycard",
		},
		{ type: "items", count: 1, weight: 1.5, rows: 1, label: "USSS - Kevlar 3", cols: 1, name: "ussskev3" },
		{ type: "items", rows: 1, weight: 0.1, count: 8, label: "Pistol Magazine", cols: 1, name: "ammo_pistol" },
	],
	weapons: {},
	clothes: {
		tshirt: {
			name: "Hauts",
			label: "Hauts",
			weight: 1,
			count: 10,
			type: "clothes",
			url: "https://assets-vision-fa.cdn.purplemaze.net/assets/Binco/Homme/Hauts/20_1.webp",
		},
	},
	hud: {
		hunger: 0.2,
		thirst: 0.5,
		maxWeight: 100,
	},
};

export const mockStateTarget = {
	...mockState,
	target: {
		name: "Carrera GT Turismo - Coffre du véhicule",
		maxWeight: 10000,
		items: mockState.items,
	},
};
